#!/bin/bash

APACHE_SITE_DIR="/etc/apache2/sites-available";

# fr: vérifie si vous êtes le root
# en: verify if you have root privilege
if ! test `id -u` -eq 0; then
	c_echo "Permission non authorisé" "red";
	exit 1
fi

# fr: colorie un message de sortie.
# en: color a output message
c_echo() {
	if [[ $2 == "red" ]]; then
		echo -e "\033[0;31m$1\033[00m"
	elif [[ $2 == "green" ]]; then
		echo -e "\033[0;32m$1\033[00m";
	else
		echo -e "\033[0;35m$1\033[00m"
	fi
}

# fr: vérifie si un programme exist, sinon vous demande si vous voulez l'installé
# en: verify if a program exist, else tell you if you want install it
prog_exist() {
if ! test `which $1`; then
	c_echo "$1 not found" "red"
	echo "You want install it? y/n: "
	read -r response
	if [[ $reponse == "y" ]]; then

		apt-get install $1 -y > /dev/null
		exit 0
	fi
	exit 1
fi
}

# fr: fonction `usage`
# en: `usage` function
usage() {

echo -e "
 usage:
 
 sudo $0 add <docroot> <servername> [--with-git]
 sudo $0 remove <servername>
 sudo $0 list
 sudo $0 has <servername>
	
 [fr]
 \033[0;4mCommande\033[00m
 add............ajout un projet
 remove.........supprimé un projet
 has............informe si le domaine exist
 list...........list tout le domaine
 \033[0;4mvaleur\033[00m
 <docroot>......répertoire ou le serveur va trouvé les fichiers à servir.
 <servername>...le nom de domaine sur projet

 \033[0;4moption\033[00m:
 --with-git.....initialise un dépot git. 
 
 [en]
 \033[0;4mCommand\033[00m
 add............add project
 remove.........remove project
 has............tell you if domaine exist
 list...........list all domaine
 \033[0;4mvalue\033[00m
 <docroot>......documentroot.
 <servername>...you project domain name.

 \033[0;4moption\033[00m:
 --with-git.....if has enabled, git repository will be initialize.

  Exemples:
	
  # add
  sudo $0 add /path/to/my/project/folder project.dev

  # remove
  sudo $0 remove project.dev
		
  \033[0;4mFork me\033[00m to https://github.com/papac/virtual.git
"
}

# fr: fonction d'ajout de configuration
# en: add configuration function
add_vhost() {
# fr: Variable global
# en: Global variable
SERVERNAME=""
HTTP=80
C=0
LOGLEV="warn"

case $# in
		
	2|3)
			if [ ! -d "$1" ]; then
				usage
				exit 1
			else
				if [ -f $APACHE_SITE_DIR/$2".conf" ]; then
					c_echo "This domaine already exist." "red"
					exit 1
				else
					DOCROOT=$1
					SERVERNAME=$2
					C=1				
				fi
			fi
	;;
	*)
			usage
			exit 1
	;;
esac

if (( $C == 1 )); then
echo "<VirtualHost *:$HTTP>
	
	ServerName $SERVERNAME
	serverAlias www.$SERVERNAME
	DocumentRoot $DOCROOT

	<Directory $DOCROOT/>
		Options Indexes Multiviews FollowSymLinks
		AllowOverride All
		require all granted
	</Directory>
	
	ErrorLog "$DOCROOT/.logs/error.log"
	CustomLog "$DOCROOT/.logs/access.log" combined
	LogLevel $LOGLEV

</VirtualHost>" > $APACHE_SITE_DIR/$SERVERNAME".conf"

	cd $APACHE_SITE_DIR
	a2ensite $SERVERNAME".conf" > /dev/null 2>&1
	if [ ! -d "$DOCROOT/.logs" ]; then
		mkdir "$DOCROOT/.logs" > /dev/null 2>&1
	fi
	if `service apache2 reload > /dev/null 2>&1`; then
		chmod 755 -R $DOCROOT
		if [[ "$3" == "--with-git" ]]; then
			if prog_exist "git"; then
				cd $DOCROOT
				git init > /dev/null
				echo "Git repository has initilazed."
			fi
		fi
		echo "127.0.0.1 $SERVERNAME www.$SERVERNAME" >> /etc/hosts
		c_echo "Project domain has created." "green"
		exit 0
	else
		c_echo "An error is comming" "red"
		a2dissite $SERVERNAME".conf" > /dev/null
		rm $APACHE_SITE_DIR/$SERVERNAME".conf"
		exit 1
	fi
else
	c_echo "An error is comming." "red"
	exit 1
fi
}

# fr: fonction de suppression de configuration
# en: delete configuration function
remove_vhost() {
	if [ -f "$APACHE_SITE_DIR/$1.conf" ]; then
		# fr: désactivation de la configuration
		# en: disable configuration
		cd $APACHE_SITE_DIR
		a2dissite "${1}.conf" > /dev/null
		service apache2 reload > /dev/null
		# fr: suppression du fichier de la configuration
		# en: delete configuration file
		rm "${1}.conf"
		# fr: suppression de l'entrer du domaine dans le fichier /etc/hosts
		# en: delete domaine name in /etc/hosts
		sed -re "/^\n?127\.0\.0\.1\s+${1}\swww.${1}\n?$/ d" < /etc/hosts > /tmp/hosts
		if [ -s /tmp/hosts ]; then
			cp /tmp/hosts /etc/hosts
		fi
		c_echo "$1: removed" "green"
		exit 0
	else
		c_echo "This domaine not exist." "red"
		exit 1
	fi
}

# busness logic
PARAM=$1

prog_exist "apache2"

if [[ $PARAM == "add" ]]; then
	if [ $# -eq "3" -o $# -eq "4" ]; then
		add_vhost $2 $3 $4
		exit 0
	else
		usage
		exit 1
	fi
elif [[ $PARAM == "remove" ]]; then
	remove_vhost $2
	exit 0
elif [[ $PARAM == "list" ]]; then
	i=0
	for file in `ls /etc/apache2/sites-enabled`; do
		i=$(expr $i + 1)
		c_echo "$i-$file" "green"
	done
	exit 0
elif [[ $PARAM == "has" ]]; then
	if [ -f "$APACHE_SITE_DIR/$2.conf" ]; then
		c_echo "domaine $2 exist." "green"
	else
		c_echo "domaine $2 not found" "red"
	fi
elif [[ $PARAM == "help" ]]; then
	usage
	exit 0
else
	usage
	exit 1
fi
